"""add foreign key to chunks

Revision ID: 6259d880cc3c
Revises: c0534b24f46f
Create Date: 2026-07-15 15:30:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "6259d880cc3c"
down_revision = "c0534b24f46f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_chunks_document_id", table_name="chunks")
    op.create_foreign_key(
        "fk_chunks_documents",
        "chunks",
        "documents",
        ["document_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index(op.f("ix_chunks_document_id"), "chunks", ["document_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunks_document_id"), table_name="chunks")
    op.drop_constraint("fk_chunks_documents", "chunks", type_="foreignkey")
    op.create_index("ix_chunks_document_id", "chunks", ["document_id"], unique=False)
    # ### end Alembic commands ###
